version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - php:/var/www/html
    depends_on:
      - php
  php:
    build: ./docker/php/
    volumes:
      - ./medical-patients-api:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - database

    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  database:
        image: mysql:8.0
        environment:
          - "MYSQL_ROOT_PASSWORD=1234"
          - "MYSQL_DATABASE=patients"
          - "DB_PORT=3306"
        volumes:
          - ./dbdata:/var/lib/mysql
        ports:
          - "33065:3306"
volumes:
  php:
